### PR TITLE
Added APIs for Visitors

### PR DESCRIPTION
**Pull request by khanalsir**

### CODE REVIEW

**Review by pratyushashukla — CHANGES_REQUESTED** [review]
What happens to visitor information if inmate is deleted?

**Comment by khanalsir** [comment]
> What happens to visitor information if inmate is deleted?

I have only implemented the basic delete api only for now.
Option 1  => We Can refactor the api to cascade delete visitors if inmate is deleted or
Option 2 => we can be to populate a dummy inmate data (with status inactive) for those visitors whose associate inmate is deleted.

I think for now we can go with option 1. What you guys suggest?

**Comment by Bluwzy** [comment]
option 1 sounds good to me

**Comment by khanalsir** [comment]
https://inmate-plus.atlassian.net/jira/software/projects/IP/boards/4?selectedIssue=IP-133
We have solved this issue in above task. We have selected option 1

**Review by suraj2597 — APPROVED** [review]

**Pull request merged**
