### PR TITLE
Added Schema for Visitor and Visit Management

### PR DESCRIPTION
**Pull request by khanalsir**

### CODE REVIEW

**Review by Bluwzy — COMMENTED** [review]
The visitorController.js is empty, any reason for that?

**Comment by khanalsir** [comment]
> The visitorController.js is empty, any reason for that?

Noted.
Sorry. I thought I would first commit the structure related to my next task so I committed the empty file. 
 Next time I would keep this in mind.
 Thank you

**Comment by Bluwzy** [comment]
No problem at all! Starting with a structured setup, even if it’s an empty file, is a good approach. It helps keep everything organized as you build out the functionality.

**Comment by khanalsir** [comment]
> No problem at all! Starting with a structured setup, even if it’s an empty file, is a good approach. It helps keep everything organized as you build out the functionality.

Thank You

**Review by pratyushashukla — APPROVED** [review]
In that case, i think it is good to merge then

**Pull request merged**
